{
 "title": "Cluster Workloads",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{clusterName=~\"$cluster_name\", phase=\"Active\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(irate({__name__=~\"node_cpu_seconds_total|windows_cpu_time_total\",mode=\"idle\", clusterName=~\"$cluster_name\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{clusterName=~\"$cluster_name\"}) / sum(node_memory_MemTotal_bytes{clusterName=~\"$cluster_name\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network errors & dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_drop_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Receive dropped"
    },
    {
     "expr": "(sum(rate(node_network_transmit_drop_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Transmit dropped"
    },
    {
     "expr": "(sum(rate(node_network_receive_errs_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Receive errors"
    },
    {
     "expr": "(sum(rate(node_network_transmit_errs_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Transmit errors"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\", clusterName=~\"$cluster_name\"}) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\", clusterName=~\"$cluster_name\"}))) * 100",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average CPU per cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(1 - (avg by (clusterName)(irate({__name__=~\"node_cpu_seconds_total|windows_cpu_time_total\",mode=\"idle\", clusterName=~\"$cluster_name\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Average CPU per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (namespace)(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Average CPU per node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((1 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\", clusterName=~\"$cluster_name\"}[$__rate_interval])))) * 100) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_requests:sum{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum by (clusterName)(node_memory_MemAvailable_bytes{clusterName=~\"$cluster_name\"})) / (sum by (clusterName)(node_memory_MemTotal_bytes{clusterName=~\"$cluster_name\"}))) * 100",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", container!=\"\", namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage per node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((1 - (sum by (instance)(node_memory_MemAvailable_bytes{clusterName=~\"$cluster_name\"})) / (sum by (instance)(node_memory_MemTotal_bytes{clusterName=~\"$cluster_name\"}))) * 100) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory requests by namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner{job=\"kube-state-metrics\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=\"$cluster_name\", container!=\"\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_requests:sum{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", container!=\"\", namespace=~\"$namespace\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_requests:sum{clusterName=\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(namespace_memory:kube_pod_container_resource_limits:sum{clusterName=\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=\"$cluster_name\", container!=\"\", namespace=~\"$namespace\"}) by (namespace) / sum(namespace_memory:kube_pod_container_resource_limits:sum{clusterName=\"$cluster_name\", namespace=~\"$namespace\"}) by (namespace)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Storage space usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum by (clusterName)(kubelet_volume_stats_capacity_bytes{clusterName=~\"$cluster_name\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"})\n  -\n  sum by (clusterName)(kubelet_volume_stats_available_bytes{clusterName=~\"$cluster_name\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"})\n\n",
     "legendFormat": "Used space ({{clusterName}})"
    },
    {
     "expr": "sum by (clusterName)(kubelet_volume_stats_available_bytes{clusterName=~\"$cluster_name\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"})",
     "legendFormat": "Free space ({{clusterName}})"
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Read - {{clusterName}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Write - {{clusterName}}"
    }
   ]
  },
  {
   "title": "Reads per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Writes per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Persistent volume claims used space per namespace",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    kubelet_volume_stats_capacity_bytes{clusterName=~\"$cluster_name\",\n    job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"}\n    -\n    kubelet_volume_stats_available_bytes{clusterName=~\"$cluster_name\",\n    job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"}\n  )\n  /\n  kubelet_volume_stats_capacity_bytes{clusterName=~\"$cluster_name\",\n  job=\"kubelet\", metrics_path=\"/metrics\", namespace=~\"$namespace\"}\n  ) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Storage I/O",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+)\", container!=\"\", clusterName=~\"$cluster_name\", namespace!=\"\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Transmit total ({{clusterName}})"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Receive total ({{clusterName}})"
    },
    {
     "expr": "(sum by (clusterName)(rate(node_network_receive_errs_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Receive errors ({{clusterName}})"
    },
    {
     "expr": "(sum by (clusterName)(rate(node_network_transmit_errs_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Transmit errors ({{clusterName}})"
    },
    {
     "expr": "(sum by (clusterName)(rate(node_network_receive_drop_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Receive dropped ({{clusterName}})"
    },
    {
     "expr": "(sum by (clusterName)(rate(node_network_transmit_drop_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) OR on() vector(0))",
     "legendFormat": "Transmit dropped ({{clusterName}})"
    }
   ]
  },
  {
   "title": "Transmit per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (instance)) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Receive per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (instance)) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Bytes received per namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bytes tansmitted per namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{clusterName=\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{clusterName=~\"$cluster_name\",namespace=~\"$namespace\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of TCP Retransmits out of all sent segments",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(node_netstat_Tcp_RetransSegs{clusterName=~\"$cluster_name\"}[$__rate_interval]) / rate(node_netstat_Tcp_OutSegs{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (instance)) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Rate of TCP SYN Retransmits out of all retransmits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(node_netstat_TcpExt_TCPSynRetrans{clusterName=~\"$cluster_name\"}[$__rate_interval]) / rate(node_netstat_Tcp_RetransSegs{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (instance)) * on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}