{
 "title": "Pod Metrics",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{clusterName=~\"$cluster_name\", phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   },
   {
    "name": "pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},pod_ip)"
    }
   },
   {
    "name": "pod_status",
    "query": {
     "query": "query_result(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"} > 0)"
    }
   },
   {
    "name": "pod_node_ip",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},host_ip)"
    }
   },
   {
    "name": "pod_node_name",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},node)"
    }
   },
   {
    "name": "pod_created_by_kind",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},created_by_kind)"
    }
   },
   {
    "name": "pod_created_by_name",
    "query": {
     "query": "label_values(kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"},created_by_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod_ip}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Running\"}) > 0",
     "legendFormat": "Running"
    },
    {
     "expr": "sum by (phase)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Failed\"}) > 0",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum by (phase)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Pending\"}) > 0",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum by (phase)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"}) > 0",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum by (phase)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", phase=~\"Succeeded\"}) > 0",
     "legendFormat": "Succeeded"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_container_status_restarts_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Created By",
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "options": {
    "content": "# ${pod_created_by_name} (${pod_created_by_kind})"
   }
  },
  { "title": "Detailed Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pod Node",
   "type": "text",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "options": {
    "content": "## Name: ${pod_node_name}\n---\n## IP: ${pod_node_ip}"
   }
  },
  {
   "title": "Containers Images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{image_spec}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "pod total"
    }
   ]
  },
  {
   "title": "Memory per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_memory_usage_bytes{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network I/O per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (io_kubernetes_pod_name)(rate(container_network_receive_bytes_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum by (io_kubernetes_pod_name)(rate(container_network_transmit_bytes_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) * -1",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(container_memory_usage_bytes{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (phase, pod)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container)(kube_pod_container_status_restarts_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}