global:
  rbac:
    create: true
    userRoles:
      aggregateToDefaultRoles: true
      create: true
  seLinux:
    enabled: false
prometheus:
  prometheusSpec:
    externalLabels:
      clusterName: "${ .ClusterName }"
    thanos:
      image: quay.io/thanos/thanos:v0.34.0
      objectStorageConfig:
        key: objstore.yml
        name: thanos-objstore-secret
  thanosService:
    enabled: true
    annotations: {}
    labels: {}
    type: NodePort
    ## gRPC port config
    clusterIP: {}
    portName: grpc
    port: 10901
    targetPort: "grpc"
    ## HTTP port config (for metrics)
    httpPortName: http
    httpPort: 10902
    targetHttpPort: "http"
    ## Port to expose on each node, if service type is NodePort
    ##
    nodePort: 30901
    httpNodePort: 30902