{
 "title": "Prometheus",
 "description": "Status of the monitoring Prometheus components",
 "tags": [ "monitoring" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(prometheus_build_info{job=~\"$job\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(prometheus_build_info{clusterName=~\"$cluster_name\", job=~\".*prometheus.*\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Pods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count\n(\n  kube_pod_container_info{clusterName=~\"$cluster_name\", container=~\"prometheus.*\"}\n) by (container, clusterName)\n",
     "legendFormat": "{{clusterName}} - {{container}}"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{clusterName=~\"$cluster_name\", job=~\"$job\"}[$__rate_interval])) by (scrape_job) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of discovered targets",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=~\"$job\", clusterName=~\"$cluster_name\"}) by (clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Scrape Interval Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\",clusterName=~\"$cluster_name\"}[$__rate_interval]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\",clusterName=~\"$cluster_name\"}[$__rate_interval]) * 1e3",
     "legendFormat": "{{clusterName}} - {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, clusterName) (rate(prometheus_target_scrapes_exceeded_body_size_limit_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} - exceeded body size limit: {{job}}"
    },
    {
     "expr": "sum by (job, clusterName) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} - exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by (job, clusterName) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} - duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by (job, clusterName) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} - out of bounds: {{job}}"
    },
    {
     "expr": "sum by (job, clusterName) (rate(prometheus_target_scrapes_sample_out_of_order_total{clusterName=\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} - out of order: {{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",clusterName=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "{{clusterName}} - {{job}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{clusterName=~\"$cluster_name\",job=~\"$job\",slice=\"inner_eval\"}[$__rate_interval])",
     "legendFormat": "{{clusterName}} - {{job}}"
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (slice, clusterName) (prometheus_engine_query_duration_seconds{quantile=\"0.9\",job=~\"$job\",clusterName=~\"$cluster_name\"}) * 1e3",
     "legendFormat": "{{clusterName}} - {{slice}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Head Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",clusterName=~\"$cluster_name\"}",
     "legendFormat": "{{clusterName}} - {{job}}"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",clusterName=~\"$cluster_name\"}",
     "legendFormat": "{{clusterName}} - {{job}}"
    }
   ]
  }
 ]
}