{
 "title": "CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server with updated metrics for version 1.7.0+.  Based on the CoreDNS dashboard by buhay.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (proto) or\nsum(rate(coredns_dns_requests_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (type) or \nsum(rate(coredns_dns_requests_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (zone) or\nsum(rate(coredns_dns_requests_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (zone)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_do_count_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval])) or\nsum(rate(coredns_dns_do_requests_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) or\nsum(rate(coredns_dns_requests_total{job=\"coredns\", clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Responses (by rcode)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (rcode) or\nsum(rate(coredns_dns_responses_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le, job))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Responses (size, udp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"udp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 50%"
    }
   ]
  },
  {
   "title": "Responses (size, tcp)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{job=\"coredns\",clusterName=~\"$cluster_name\",proto=\"tcp\"}[$__rate_interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}: 50%"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Cache (size)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_size{job=\"coredns\",clusterName=~\"$cluster_name\"}) by (type) or\nsum(coredns_cache_entries{job=\"coredns\",clusterName=~\"$cluster_name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (type)",
     "legendFormat": "hits: {{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{job=\"coredns\",clusterName=~\"$cluster_name\"}[$__rate_interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}