{
 "title": "etcd",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{clusterName=~\"$cluster_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(process_cpu_seconds_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(etcd_mvcc_db_total_size_in_bytes{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName, le))",
     "legendFormat": "WAL fsync: {{clusterName}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName, le))",
     "legendFormat": "DB fsync: {{clusterName}}"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{clusterName=~\"$cluster_name\", job=\"kube-etcd\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(changes(etcd_server_leader_changes_seen_total{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[1d])) by (clusterName)",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Peer Round Trip Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (clusterName, le) (rate(etcd_network_peer_round_trip_time_seconds_bucket{clusterName=~\"$cluster_name\", job=\"kube-etcd\"}[$__rate_interval])))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  }
 ]
}